const request = require("request");
const mongoose = require('mongoose');
const nutrientSchema = require("./userModel");
const connectDB = require("./db");

const indianFoods = [
  "Biryani",
  "Butter Chicken",
  "Chole Bhature",
  "Pani Puri",
  "Aloo Paratha",
  "Dosa",
  "Samosa",
  "Pav Bhaji",
  "Palak Paneer",
  "Rajma",
  "Tandoori Chicken",
  "Idli",
  "Vada",
  "Rogan Josh",
  "Kadhai Paneer",
  "Bhel Puri",
  "Momos",
  "Pulao",
  "Aloo Gobi",
  "Chana Masala",
  "Gulab Jamun",
  "Kheer",
  "Pesarattu",
  "Methi Thepla",
  "Hyderabadi Haleem",
  "Dhokla",
  "Pesarattu",
  "Mutton Curry",
  "Shahi Paneer",
  "Sambar",
  "Rava Kesari",
  "Methi Paratha",
  "Prawn Curry",
  "Methi Malai Murg",
  "Baingan Bharta",
  "Naan",
  "Chapati",
  "Pongal",
  "Vermicelli Upma",
  "Aloo Methi",
  "Mango Lassi",
  "Mysore Pak",
  "Kadhi Pakora",
  "Macher Jhol",
  "Puri Sabzi",
  "Kothu Parotta",
  "Sichuan Rice",
  "Litti Chokha",
  "Sarson Da Saag",
  "Makki Di Roti",
  "Malai Kofta",
  "Jalebi",
  "Pakoras",
  "Gobi Manchurian",
  "Baida Roti",
  "Tandoori Roti",
  "Coconut Rice",
  "Mutton Biryani",
  "Cabbage Sabzi",
  "Aloo Tikki",
  "Kaladi Kulcha",
  "Vegetable Biryani",
  "Nihari",
  "Gajar Halwa",
  "Sichuan Noodles",
  "Roti",
  "Kachori",
  "Chana Chaat",
  "Mithai",
  "Murg Musallam",
  "Dal Tadka",
  "Khichdi",
  "Methi Thepla",
  "Sweets like Barfi",
  "Rava Dosa",
  "Lassi",
  "Dum Aloo",
  "Soya Chaap",
  "Bajra Roti",
  "Methi Pulao",
  "Kebabs",
  "Tamarind Rice",
  "Mango Pickle",
  "Moong Dal Chilla",
  "Ragi Roti",
  "Rajma Chawal",
  "Chole",
  "Zarda",
  "Sindhi Biryani",
  "Karela Sabzi",
  "Kadhi",
  "Methi Pakora",
  "Pineapple Kesari",
  "Chana Pulao",
  "Tamatar ki Chutney",
  "Gujrati Thali",
  "Dal Baati Churma",
  "Bhindi Masala",

  "Sundal",
  "Korma",
  "Lassi",
  "Prawn Masala",
  "Mutton Keema",
  "Roti with Dal",
  "Samosa Chaat",
  "Gajar Methi Sabzi",
  "Kachaudi",
  "Khoya",
  "Banarasi Paan",
  "Kaddu Ki Sabzi",
  "Sabudana Khichdi",
  "Pineapple Raita",
  "Tamarind Chutney",
  "Paneer Butter Masala",
  "Khatti Meethi Aloo",
  "Dahi Puri",
  "Biryani Pulao",
  "Methi Murg",
  "Chana Daal",
  "Lemon Rice",
  "Khandvi",
  "Dal Paratha",
  "Bajra Khichdi",
  "Moong Dal Halwa",
  "Jalebi Rabri",
  "Vegetable Seekh Kebab",
  "Chana Biryani",
  "Papad",
  "Vegetable Korma",
  "Sweet Lassi",
  "Spicy Bhel Puri",
  "Shira",
  "Bisi Bele Bath",
  "Mango Chutney",
  "Pesarattu Dosa",
  "Sattu Paratha",
  "Methi Thepla",
  "Pineapple Fried Rice",
  "Kothimbir Wadi",
  "Tandoori Paneer",
  "Dum Aloo Kashmiri",
  "Chana Masala Chaat",
  "Methi Dal",
  "Moong Dal Pancake",
  "Dal Khichdi",
  "Kachaudi Sabzi",
  "Vegetable Pakora",
  "Lassi with Ice Cream",
  "Masala Papad",
  "Dosas with Coconut Chutney",
  "Aloo Baingan",
  "Aloo Methi Paratha",
  "Ginger Chutney",
  "Gulab Jamun with Rabri",
  "Chole Pulao",
  "Steamed Idli with Sambhar",
  "Pav Bhaji with Butter",
  "Tandoori Mushroom",
  "Sattvik Thali",
  "Bhutte ka Kees",
  "Khichda",
  "Lassi with Rose Syrup",
  "Soya Keema",
  "Bhel Puri with Boondi",
  "Spicy Prawn Fry",
  "Batata Vada",
  "Chana Tikki",
  "Methi Malai Murg",
  "Methi Thepla with Pickle",
  "Moth Beans Pulao",
  "Baingan Bharta with Yogurt",
  "Sindhi Karhi",
  "Mixed Vegetable Paratha",
  "Ragi Mudde",
  "Vegetable Pakoras",
  "Sundal with Coconut",
  "Rasam with Rice",
  "Aloo Chaat",
  "Mango Rice",
  "Cabbage Pakora",
  "Methi Stuffed Paratha",
  "Macher Bhorta",
  "Chana Curry",
  "Chutney Sandwich",
  "Pesarattu with Upma",
  "Vegan Dosa",
  "Baked Samosa",
  "Kadhi with Pakora",
  "Gajar Ka Achar",
  "Mango Lassi",
  "Kachori with Aloo Sabzi",
  "Pudina Paratha",
  "Tandoori Roti with Paneer",
  "Methi Gobi Paratha",
  "Pav Bhaji with Cheese",
  "Pesarattu with Coconut Chutney",
  "Dal Amritsari",
  "Rava Idli with Sambar",
  "Lentil Soup",
  "Fried Moong Dal",
  "Dal Makhani",
  "Methi Dhokla",
  "Tandoori Paneer Tikka",
  "Vegetable Kebab",
  "Moong Dal Khichdi",
  "Tandoori Gobhi",
  "Mango Lassi",
  "Malai Barfi",
  "Coconut Laddu",
  "Aloo Tikki Chaat",
  "Vegetable Sambar",
  "Alu Gobi Masala",
  "Khandvi with Coconut",
  "Bhindi Do Pyaza",
  "Chana Chaat",
  "Chana Dal Pulao",
  "Dal with Chapati",
  "Veg Pulao",
  "Steamed Momo",
  "Kaju Katli",
  "Boondi Raita",
  "Gajar Halwa with Milk",
  "Aloo Tamatar Sabzi",
  "Methi Paratha with Yogurt",
  "Muthia",
  "Methi Masala Roti",
  "Thalipeeth",
  "Pav Bhaji with Puri",
  "Vermicelli Biryani",
  "Kalaadi Roti",
  "Daal Roti",
  "Vegetable Cheela",
  "Methi Murg",
  "Khoya Malpua",
  "Amritsari Macchi",
  "Vegetable Kolhapuri",
  "Fried Paneer",
  "Cucumber Raita",
  "Onion Pakora",
  "Dum Keema",
  "Chana Pulao",
  "Bengali Macher Jhol",
  "Pesarattu Dosa",
  "Vada with Sambhar",
  "Chana Chaat",
  "Alu Ke Parathe",
  "Methi Bhaji",
  "Mushroom Curry",
  "Methi Dal",
  "Chutney and Paratha",
  "Pork Vindaloo",
  "Methi Patta Rice",
  "Paratha with Curd",
  "Paneer Tikka",
  "Lassi with Butter",
  "Chana Pulao",
  "Chana with Naan",
  "Saag Aloo",
  "Methi Malai Murg",
  "Chole Bhature",
  "Aloo Gobi",
  "Khoya Gajar",
  "Vegetable Pakora with Green Chutney",
  "Methi Masala",
  "Methi Bhaji",
  "Kadhi Chawal",
  "Aloo Tikki with Yogurt",
  "Chana Methi",
  "Vegetable Seekh Kebab",
  "Gajar Ka Halwa",
  "Steamed Rice",
  "Aloo Tikka",
  "Vegetable Dhokla",

  "Vermicelli Upma",
  "Aloo Baingan",
  "Kadhi Pakora",
  "Gobi Manchurian",
  "Mutton Seekh Kebab",
  "Methi Paratha with Pickle",
  "Vermicelli Kheer",
  "Rava Pongal",
  "Rajma Chawal",
  "Chole Chawal",
  "Tandoori Naan",
  "Chana Dal Tikki",
  "Dum Pukht Biryani",
  "Chana Masala with Rice",
  "Pineapple Raita",
  "Aloo Gobi",
  "Chana Daal with Spinach",
  "Tandoori Mushroom",
  "Sambar Rice",
  "Chana Tikki Chaat",
  "Maharashtrian Thali",
  "Pav Bhaji with Cheese",
  "Vegetable Jalfrezi",
  "Rawa Kesari",
  "Kadhi with Rice",
  "Vada Pav",
  "Aloo Paratha with Yogurt",
  "Tamarind Rice with Fryums",
  "Vegetable Kofta Curry",
  "Vegetable Hyderabadi Biryani",
  "Bajra Roti with Ghee",
  "Mutton Rogan Josh",
  "Fried Aloo",
  "Vegetable Samosa",
  "Tamarind Pulav",
  "Pav Bhaji with Butter",
  "Pista Kulfi",
  "Lassi with Mango",
  "Methi Gobi",
  "Kachaudi with Chole",
  "Hyderabadi Biryani",
  "Chana Chole with Chapati",
  "Rawa Dosa",
  "Methi Pulao",
  "Fried Gobi Manchurian",
  "Vegetable Chettinad",
  "Aloo Methi Paratha",
  "Pineapple Sweet",
  "Pesarattu with Ginger Chutney",
  "Methi Gobi Paratha",
  "Prawn Tikka",
  "Kaddu Masala",
  "Kachori with Tamarind Chutney",
  "Dal with Aloo",
  "Kothimbir Wadi",
  "Baida Roti with Egg",
  "Litti Chokha",
  "Amritsari Fish",
  "Methi Thepla with Curd",
  "Kadhi Chawal",
  "Aloo Tamatar Ki Sabzi",
  "Hing Ke Parathe",
  "Chana Bhature",
  "Kachumber Salad",
  "Shahi Paneer",
  "Methi Malai Murg",
  "Malai Murg",
  "Kuttu Ka Paratha",
  "Gajar Halwa ",
  "Methi Pulao ",
  "Kadhi Pakora",
  "Ginger Dal",
  "Tandoori Gobi",
  "Kashmiri Dum Aloo",
  "Tamatar Ka Bharta",
  "Korma",
  "Vermicelli Upma",
  "Kadhai Paneer",
  "Papad and Pickle",
  "Methi Masala Paratha",
  "Chana Masala",
  "Kachaudi",
  "Lassi",
  "Methi Bhaji",
  "Shahi Tukda",
  "Vermicelli Pudding",
  "Kachaudi",
  "Khoya Paneer",
  "Moong Dal ",
  "Fried Idli",
  "Methi Pulao",
  "Kadhai Paneer",
  "Baingan Ka Bharta",
  "Vegetable Korma",
  "Masoor Dal",
  "Thalipeeth",
  "Chole",
  "Puri",
  "Methi Roti",
  "Karela Sabzi",
  "Chana Biryani",
  "Mushroom Masala",
  "Cucumber",
  "Tomato Salad",
  "Dal",
  "Aloo Palak",
  "Methi Thepla",
  "Rava Dosa",
  "Pineapple Rice",
  "Dum Aloo",
  "Idli",
  "Aloo Tikki",
  "Spicy Paneer Tikka",
  "Vegetable Pulao",
  "Kadhi",
  "Cheese Naan",
  "Methi Dal",
  "Lamb Biryani",
  "Moong Dal Chilla",
  "Sichuan Paneer",
  "Aloo Tikki",
  "Vegetable Soup",
  "Gulab Jamun",
  "Aloo Gobhi",
  "Cabbage Paratha",
  "Steamed Momo",
  "Kadhi Pakora",
  "Sundal",
  "Chana Pulao",
  "Methi Gobi Masala",
  "Sichuan Rice",
  "Pav Bhaji",
  "Khichdi",
  "Dum Ka Murg",
  "Masala Papad",
  "Methi Malai ",
  "Aloo Ka Paratha",
  "Palak Paratha",
  "Methi Pulao",
  "Tandoori Aloo",
  "Vada",
  "Kachaudi",
  "Methi Murg",
  "Papad",
  "Gulab Jamun",
  "Pineapple Pudding",
  "Aloo Gobi",
  "Baingan Bharta",
  "Biryani ",
  "Shahi Paneer",
  "Methi Kachori",
  "Pesarattu",
  "Cheese Paratha",
  "Rava Lassi",
  "Rawa Khichdi",
  "Paneer Bhurji",
  "Methi Ke Gulgule",
  "Methi Masala Rice",
  "Bhindi",
  "Vermicelli",
  "Pav Bhaji",
  "Pulao",
  "Dosa",
  "Sambar",
  "Tamarind Rice",
  "Veg Korma",
  "Kachori",
  "Butter Chicken",
  "Lamb Seekh Kebab",
  "Chana Masala",
  "Gulab Jamun",
  "Chana Chole",
  "Chana Dal",
  "Methi Murg",
  "Vegetable Dosa",
  "Lamb Kofta Curry",
  "Methi Malai",
  "Methi Thepla",
  "Green Chutney",
  "Rava Masala Dosa",
  "Vegetable Upma",
  "Methi Chapati",
  "Aloo Sabzi",
  "Dal Bati",
  "Korma",
  "Paneer Pasanda",
  "Chana Chole",
];
const foodItems = [
    // Fruits
    "Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry", "Blueberry", "Raspberry", "Blackberry",
    "Watermelon", "Cantaloupe", "Honeydew Melon", "Kiwi", "Papaya", "Peach", "Plum", "Apricot", "Cherry", "Pomegranate",
    "Fig", "Guava", "Pear", "Lychee", "Dragon Fruit", "Coconut", "Passion Fruit", "Jackfruit", "Avocado", "Cranberry",
    "Mulberry", "Starfruit", "Persimmon", "Gooseberry", "Tamarind", "Date", "Jujube", "Cactus Pear", "Custard Apple",
    "Longan", "Sapodilla", "Ugli Fruit", "Durian", "Feijoa", "Breadfruit", "Mangosteen", "Nectarine", "Elderberry",
 "Boysenberry", "Cloudberry",  "Rambutan", "Ackee",
    
    // Dry Fruits & Nuts
    "Almonds", "Cashews", "Walnuts", "Pistachios", "Hazelnuts", "Macadamia Nuts", "Brazil Nuts", "Pine Nuts",
    "Pecans", "Chestnuts", "Peanuts", "Sunflower Seeds", "Pumpkin Seeds", "Chia Seeds", "Flax Seeds", "Sesame Seeds",
    "Watermelon Seeds", "Lotus Seeds", "Coconut Flakes", "Dried Apricots", "Dried Figs", "Dried Dates", "Raisins",
    "Sultanas", "Currants", "Prunes", "Dried Cranberries", "Dried Blueberries", "Dried Goji Berries", "Dried Mulberries",
    "Dried Mango", "Dried Pineapple", "Dried Papaya", "Dried Banana Chips", "Dried Apple Slices", "Dried Pears",
    "Dried Cherries", "Dried Blackberries", "Dried Raspberries", "Dried Starfruit", "Dried Kiwi", "Dried Persimmon",
    "Dried Coconut", "Dried Lychee", "Dried Longan", "Dried Gooseberries", "Dried Jackfruit",
     "Dried Tamarind", "Dried Elderberries", "Dried Olive", "Dried Prickly Pear",
     "Dried Cranberry Hibiscus", "Dried Jujube", "Dried Sapodilla", "Dried Rambutan",
    "Dried Ackee", "Dried Cloudberry",
  
    // Milk & Dairy Products
    "Milk", "Whole Milk", "Skimmed Milk", "Low-Fat Milk", "Almond Milk", "Soy Milk", "Coconut Milk", "Oat Milk",
    "Rice Milk", "Cashew Milk", "Goat Milk", "Buffalo Milk", "Camel Milk", "Yak Milk", "Sheep Milk",
    "Condensed Milk", "Evaporated Milk", "Powdered Milk", "Flavored Milk", "Chocolate Milk", "Strawberry Milk",
    "Vanilla Milk", "Banana Milk", "Coffee Milk", "Kefir", "Buttermilk", "Lassi", "Paneer", "Cheese", "Cottage Cheese",
    "Ricotta Cheese", "Mozzarella Cheese", "Cheddar Cheese", "Parmesan Cheese", "Swiss Cheese", "Brie Cheese",
    "Gouda Cheese", "Blue Cheese", "Feta Cheese", "Cream Cheese", "Provolone Cheese", "Gruyère Cheese", "Monterey Jack Cheese",
    "Pepper Jack Cheese", "Camembert Cheese", "Colby Cheese", "Havarti Cheese", "Manchego Cheese", "Roquefort Cheese",
    "Gorgonzola Cheese", "Edam Cheese", "Limburger Cheese", "Queso Fresco", "Mascarpone", "Halloumi", "Burrata",
    "Yogurt", "Greek Yogurt", "Frozen Yogurt", "Curd", "Sour Cream", "Butter", "Ghee",
    "Whipped Cream", "Clotted Cream", "Milk Powder", "Custard", "Milkshake", "Ice Cream", "Whey Protein",
    "Casein Protein", "Milk Pudding", "Dulce de Leche", "Sweetened Condensed Milk", "Caramelized Milk", "Milk Chocolate",
     "Milk Tea", "Bubble Tea", "Turmeric Milk", "Golden Milk", "Horchata", "Eggnog",
    "Traditional Buttermilk", "Soft Cheese", "Hard Cheese", "Artisan Cheese", "Processed Cheese"
  ];
  
const data = [
  { attr_id: 301, name: "Calcium" },
  { attr_id: 205, name: "Carbohydrate" },
  { attr_id: 601, name: "Cholesterol" },
  { attr_id: 208, name: "Energy" },
  { attr_id: 606, name: "Fatty_acids_total_saturated" },
  { attr_id: 204, name: "Total_lipid_fat" },
  { attr_id: 605, name: "Fatty_acids_total_trans" },
  { attr_id: 303, name: "Iron_Fe" },
  { attr_id: 291, name: "Fiber_total_dietary" },
  { attr_id: 306, name: "Potassium_K" },
  { attr_id: 307, name: "Sodium_Na" },
  { attr_id: 203, name: "Protein" },
  { attr_id: 269, name: "Sugars_total" },
  { attr_id: 539, name: "Sugars_added" },
  { attr_id: 324, name: "Vitamin_D" },
  { attr_id: 299, name: "Sugar_Alcohol" },
  { attr_id: 1001, name: "Erythritol" },
  { attr_id: 1006, name: "Allulose" },
  { attr_id: 1002, name: "Glycerin" },
  { attr_id: 290, name: "Xylitol" },
  { attr_id: 261, name: "Sorbitol" },
  { attr_id: 260, name: "Mannitol" },
  { attr_id: 1003, name: "Maltitol" },
  { attr_id: 1004, name: "Isomalt" },
  { attr_id: 1005, name: "Lactitol" },
  { attr_id: 513, name: "Alanine" },
  { attr_id: 221, name: "Alcohol_ethyl" },
  { attr_id: 511, name: "Arginine" },
  { attr_id: 207, name: "Ash" },
  { attr_id: 514, name: "Aspartic_acid" },
  { attr_id: 454, name: "Betaine" },
  { attr_id: 262, name: "Caffeine" },
  { attr_id: 639, name: "Campesterol" },
  { attr_id: 322, name: "Carotene_alpha" },
  { attr_id: 321, name: "Carotene_beta" },
  { attr_id: 326, name: "Vitamin_D3_cholecalciferol" },
  { attr_id: 421, name: "Choline_total" },
  { attr_id: 334, name: "Cryptoxanthin_beta" },
  { attr_id: 312, name: "Copper_Cu" },
  { attr_id: 507, name: "Cystine" },
  { attr_id: 325, name: "Vitamin_D2_ergocalciferol" },
  { attr_id: 645, name: "Fatty_acids_total_monounsaturated" },
  { attr_id: 646, name: "Fatty_acids_total_polyunsaturated" },
  { attr_id: 693, name: "Fatty_acids_total_trans_monoenoic" },
  { attr_id: 695, name: "Fatty_acids_total_trans_polyenoic" },
  { attr_id: 313, name: "Fluoride_F" },
  { attr_id: 417, name: "Folate_total" },
  { attr_id: 431, name: "Folic_acid" },
  { attr_id: 435, name: "Folate_DFE" },
  { attr_id: 432, name: "Folate_food" },
  { attr_id: 212, name: "Fructose" },
  { attr_id: 287, name: "Galactose" },
  { attr_id: 515, name: "Glutamic_acid" },
  { attr_id: 211, name: "Glucose_dextrose" },
  { attr_id: 516, name: "Glycine" },
  { attr_id: 512, name: "Histidine" },
  { attr_id: 521, name: "Hydroxyproline" },
  { attr_id: 503, name: "Isoleucine" },
  { attr_id: 213, name: "Lactose" },
  { attr_id: 504, name: "Leucine" },
  { attr_id: 338, name: "Lutein_zeaxanthin" },
  { attr_id: 337, name: "Lycopene" },
  { attr_id: 505, name: "Lysine" },
  { attr_id: 214, name: "Maltose" },
  { attr_id: 506, name: "Methionine" },
  { attr_id: 304, name: "Magnesium_Mg" },
  { attr_id: 428, name: "Menaquinone_4" },
  { attr_id: 315, name: "Manganese_Mn" },
  { attr_id: 406, name: "Niacin" },
  { attr_id: 573, name: "Vitamin_E_added" },
  { attr_id: 578, name: "Vitamin_B_12_added" },
  { attr_id: 257, name: "Adjusted_Protein" },
  { attr_id: 305, name: "Phosphorus_P" },
  { attr_id: 410, name: "Pantothenic_acid" },
  { attr_id: 508, name: "Phenylalanine" },
  { attr_id: 636, name: "Phytosterols" },
  { attr_id: 517, name: "Proline" },
  { attr_id: 319, name: "Retinol" },
  { attr_id: 405, name: "Riboflavin" },
  { attr_id: 317, name: "Selenium_Se" },
  { attr_id: 518, name: "Serine" },
  { attr_id: 641, name: "Beta_sitosterol" },
  { attr_id: 209, name: "Starch" },
  { attr_id: 638, name: "Stigmasterol" },
  { attr_id: 210, name: "Sucrose" },
  { attr_id: 263, name: "Theobromine" },
  { attr_id: 404, name: "Thiamin" },
  { attr_id: 502, name: "Threonine" },
  { attr_id: 323, name: "Vitamin_E_alpha_tocopherol" },
  { attr_id: 341, name: "Tocopherol_beta" },
  { attr_id: 343, name: "Tocopherol_delta" },
  { attr_id: 342, name: "Tocopherol_gamma" },
  { attr_id: 501, name: "Tryptophan" },
  { attr_id: 509, name: "Tyrosine" },
  { attr_id: 510, name: "Valine" },
  { attr_id: 318, name: "Vitamin_A_IU" },
  { attr_id: 320, name: "Vitamin_A_RAE" },
  { attr_id: 418, name: "Vitamin_B_12" },
  { attr_id: 415, name: "Vitamin_B_6" },
  { attr_id: 401, name: "Vitamin_C_total_ascorbic_acid" },
  { attr_id: 328, name: "Vitamin_D_D2_D3" },
  { attr_id: 430, name: "Vitamin_K_phylloquinone" },
  { attr_id: 429, name: "Dihydrophylloquinone" },
  { attr_id: 255, name: "Water" },
  { attr_id: 309, name: "Zinc_Zn" },
];

// const arr = [];
// const makeNutritionixRequest = (item) => {

//   return new Promise((resolve, reject) => {
//     const options = {
//       method: 'POST',
//       url: 'https://trackapi.nutritionix.com/v2/natural/nutrients',
//       headers: {
//         'Content-Type': 'application/json',
//         'x-app-id': '1ebff491',
//         'x-app-key': 'a95ebbb5ca84cc23b014668f33ea8f91',
//       },
//       body: JSON.stringify({ query: item }),
//     };

//     request(options, (error, response, body) => {
//       if (error) {
//         return reject(error);
//       }
//       resolve(JSON.parse(body));
//     });
//   });
// };
// for (let i=0;i<100;i++) {
//     let item = indianFoods[i];
//     console.log(new Date().toLocaleString());
//     var str = "";
//     const food=[];
//     food.push({name:foodname,value:item});
//     for(var ch of item){
//         if(ch === " "){
//             str+=ch;
//         }
//         if((ch >="a" && ch<="z") || (ch>="A" && ch<="Z")){
//             str+=ch;
//         }
//     }
//     console.log(str);
//     const response = await makeNutritionixRequest(str);
//     if (!response.ok) {
//         arr.push(item);
//     }
//     else{
//         const result = response;
//         result.foods[0].full_nutrients.forEach((nutrient) => {
//             const nutrientName = data.find((n) => n.attr_id === nutrient.attr_id).name;
//             food.push({ name: nutrientName, value: nutrient.value });
//         });
//         food.push({name:quantity,value:result.foods[0].alt_measures[0].serving_weight})
//         try{
//             const {foodname,quantity,Calcium,
//                 Carbohydrate,
//                 Cholesterol,
//                 Fatty_acids_total_saturated,
//                 Total_lipid_fat,
//                 Fatty_acids_total_trans,
//                 Iron_Fe,
//                 Fiber_total_dietary,
//                 Potassium_K,
//                 Sodium_Na,
//                 Protein,
//                 Sugars_total,
//                 Sugars_added,
//                 Vitamin_D,
//                 Sugar_Alcohol,
//                 Erythritol,
//                 Allulose,
//                 Glycerin,
//                 Xylitol,
//                 Sorbitol,
//                 Mannitol,
//                 Maltitol,
//                 Isomalt,
//                 Lactitol,
//                 Alanine,
//                 Alcohol_ethyl,
//                 Arginine,
//                 Ash,
//                 Aspartic_acid,
//                 Betaine,
//                 Caffeine,
//                 Campesterol,
//                 Carotene_alpha,
//                 Carotene_beta,
//                 Vitamin_D3_cholecalciferol,
//                 Choline_total,
//                 Cryptoxanthin_beta,
//                 Copper_Cu,
//                 Cystine,
//                 Energy,
//                 Vitamin_D2_ergocalciferol,
//                 Fatty_acids_total_monounsaturated,
//                 Fatty_acids_total_polyunsaturated,
//                 Fatty_acids_total_trans_monoenoic,
//                 Fatty_acids_total_trans_polyenoic,
//                 Fluoride_F,
//                 Folate_total,
//                 Folic_acid,
//                 Folate_DFE,
//                 Folate_food,
//                 Fructose,
//                 Galactose,
//                 Glutamic_acid,
//                 Glucose_dextrose,
//                 Glycine,
//                 Histidine,
//                 Hydroxyproline,
//                 Isoleucine,
//                 Lactose,
//                 Leucine,
//                 Lutein_zeaxanthin,
//                 Lycopene,
//                 Lysine,
//                 Maltose,
//                 Methionine,
//                 Magnesium_Mg,
//                 Menaquinone_4,
//                 Manganese_Mn,
//                 Niacin,
//                 Vitamin_E_added,
//                 Vitamin_B_12_added,
//                 Adjusted_Protein,
//                 Phosphorus_P,
//                 Pantothenic_acid,
//                 Phenylalanine,
//                 Phytosterols,
//                 Proline,
//                 Retinol,
//                 Riboflavin,
//                 Selenium_Se,
//                 Serine,
//                 Beta_sitosterol,
//                 Starch,
//                 Stigmasterol,
//                 Sucrose,
//                 Theobromine,
//                 Thiamin,
//                 Threonine,
//                 Vitamin_E_alpha_tocopherol,
//                 Tocopherol_beta,
//                 Tocopherol_delta,
//                 Tocopherol_gamma,
//                 Tryptophan,
//                 Tyrosine,
//                 Valine,
//                 Vitamin_A_IU,
//                 Vitamin_A_RAE,
//                 Vitamin_B_12,
//                 Vitamin_B_6,
//                 Vitamin_C_total_ascorbic_acid,
//                 Vitamin_D_D2_D3,
//                 Vitamin_K_phylloquinone,
//                 Dihydrophylloquinone,
//                 Water,
//                 Zinc_Zn} = food;

//                 foodname=item;
//             const newUser = new nutrientSchema({foodname,quantity,Calcium,
//                 Carbohydrate,
//                 Cholesterol,
//                 Fatty_acids_total_saturated,
//                 Total_lipid_fat,
//                 Fatty_acids_total_trans,
//                 Iron_Fe,
//                 Fiber_total_dietary,
//                 Potassium_K,
//                 Sodium_Na,
//                 Protein,
//                 Sugars_total,
//                 Sugars_added,
//                 Vitamin_D,
//                 Sugar_Alcohol,
//                 Erythritol,
//                 Allulose,
//                 Glycerin,
//                 Xylitol,
//                 Sorbitol,
//                 Mannitol,
//                 Maltitol,
//                 Isomalt,
//                 Lactitol,
//                 Alanine,
//                 Alcohol_ethyl,
//                 Arginine,
//                 Ash,
//                 Aspartic_acid,
//                 Betaine,
//                 Caffeine,
//                 Campesterol,
//                 Carotene_alpha,
//                 Carotene_beta,
//                 Vitamin_D3_cholecalciferol,
//                 Choline_total,
//                 Cryptoxanthin_beta,
//                 Copper_Cu,
//                 Cystine,
//                 Energy,
//                 Vitamin_D2_ergocalciferol,
//                 Fatty_acids_total_monounsaturated,
//                 Fatty_acids_total_polyunsaturated,
//                 Fatty_acids_total_trans_monoenoic,
//                 Fatty_acids_total_trans_polyenoic,
//                 Fluoride_F,
//                 Folate_total,
//                 Folic_acid,
//                 Folate_DFE,
//                 Folate_food,
//                 Fructose,
//                 Galactose,
//                 Glutamic_acid,
//                 Glucose_dextrose,
//                 Glycine,
//                 Histidine,
//                 Hydroxyproline,
//                 Isoleucine,
//                 Lactose,
//                 Leucine,
//                 Lutein_zeaxanthin,
//                 Lycopene,
//                 Lysine,
//                 Maltose,
//                 Methionine,
//                 Magnesium_Mg,
//                 Menaquinone_4,
//                 Manganese_Mn,
//                 Niacin,
//                 Vitamin_E_added,
//                 Vitamin_B_12_added,
//                 Adjusted_Protein,
//                 Phosphorus_P,
//                 Pantothenic_acid,
//                 Phenylalanine,
//                 Phytosterols,
//                 Proline,
//                 Retinol,
//                 Riboflavin,
//                 Selenium_Se,
//                 Serine,
//                 Beta_sitosterol,
//                 Starch,
//                 Stigmasterol,
//                 Sucrose,
//                 Theobromine,
//                 Thiamin,
//                 Threonine,
//                 Vitamin_E_alpha_tocopherol,
//                 Tocopherol_beta,
//                 Tocopherol_delta,
//                 Tocopherol_gamma,
//                 Tryptophan,
//                 Tyrosine,
//                 Valine,
//                 Vitamin_A_IU,
//                 Vitamin_A_RAE,
//                 Vitamin_B_12,
//                 Vitamin_B_6,
//                 Vitamin_C_total_ascorbic_acid,
//                 Vitamin_D_D2_D3,
//                 Vitamin_K_phylloquinone,
//                 Dihydrophylloquinone,
//                 Water,
//                 Zinc_Zn})
//             await newUser.save();
//             res.status(200).json(newUser)
//         }
//         catch(err){
//             res.status(500).json({
//                 success:false,
//                 message:err.message
//             })
//         }
//     }

// }

const arr = [];

const makeNutritionixRequest = (item) => {
  return new Promise((resolve, reject) => {
    const options = {
      method: "POST",
      url: "https://trackapi.nutritionix.com/v2/natural/nutrients",
      headers: {
        "Content-Type": "application/json",
        
      },
      body: JSON.stringify({ query: item }),
    };

    request(options, (error, response, body) => {
      if (error) {
        return reject(error);
      }
      if (response.statusCode !== 200) {
        return reject(
          new Error(`Request failed with status code ${response.statusCode}`)
        );
      }
      resolve(JSON.parse(body));
    });
  });
};

const processFoodItem = async (item) => {
  try {
    console.log(new Date().toLocaleString());
    let str = item.replace(/[^a-zA-Z\s]/g, ""); // Remove non-alphabetic characters
    console.log(str);

    const response = await makeNutritionixRequest(str);
    const result = response;
    console.log(result);

    const food = [];
    const foodname = item;
    const quantity = result.foods[0].alt_measures[0].serving_weight;

    food.push({ name: foodname, value: item });
    result.foods[0].full_nutrients.forEach((nutrient) => {
        const nutrientMapping = data.find((n) => n.attr_id === nutrient.attr_id);
        if (!nutrientMapping) {
          console.log(`Missing nutrient ID: ${nutrient.attr_id}`);
        }
        const nutrientName = nutrientMapping?.name || `Unknown Nutrient (${nutrient.attr_id})`;
        food.push({ name: nutrientName, value: nutrient.value });
      });
    food.push({ name: "quantity", value: quantity });
    console.log(food);

    const nutrientData = {
        foodname,
        quantity,
        Calcium: food.find((n) => n.name === "Calcium")?.value,
        Carbohydrate: food.find((n) => n.name === "Carbohydrate")?.value,
        Cholesterol: food.find((n) => n.name === "Cholesterol")?.value,
        Energy: food.find((n) => n.name === "Energy")?.value,
        Fatty_acids_total_saturated: food.find(
          (n) => n.name === "Fatty_acids_total_saturated"
        )?.value,
        Total_lipid_fat: food.find((n) => n.name === "Total_lipid_fat")?.value,
        Fatty_acids_total_trans: food.find(
          (n) => n.name === "Fatty_acids_total_trans"
        )?.value,
        Iron_Fe: food.find((n) => n.name === "Iron_Fe")?.value,
        Fiber_total_dietary: food.find((n) => n.name === "Fiber_total_dietary")?.value,
        Potassium_K: food.find((n) => n.name === "Potassium_K")?.value,
        Sodium_Na: food.find((n) => n.name === "Sodium_Na")?.value,
        Protein: food.find((n) => n.name === "Protein")?.value,
        Sugars_total: food.find((n) => n.name === "Sugars_total")?.value,
        Sugars_added: food.find((n) => n.name === "Sugars_added")?.value,
        Vitamin_D: food.find((n) => n.name === "Vitamin_D")?.value,
        Sugar_Alcohol: food.find((n) => n.name === "Sugar_Alcohol")?.value,
        Erythritol: food.find((n) => n.name === "Erythritol")?.value,
        Allulose: food.find((n) => n.name === "Allulose")?.value,
        Glycerin: food.find((n) => n.name === "Glycerin")?.value,
        Xylitol: food.find((n) => n.name === "Xylitol")?.value,
        Sorbitol: food.find((n) => n.name === "Sorbitol")?.value,
        Mannitol: food.find((n) => n.name === "Mannitol")?.value,
        Maltitol: food.find((n) => n.name === "Maltitol")?.value,
        Isomalt: food.find((n) => n.name === "Isomalt")?.value,
        Lactitol: food.find((n) => n.name === "Lactitol")?.value,
        Alanine: food.find((n) => n.name === "Alanine")?.value,
        Alcohol_ethyl: food.find((n) => n.name === "Alcohol_ethyl")?.value,
        Arginine: food.find((n) => n.name === "Arginine")?.value,
        Ash: food.find((n) => n.name === "Ash")?.value,
        Aspartic_acid: food.find((n) => n.name === "Aspartic_acid")?.value,
        Betaine: food.find((n) => n.name === "Betaine")?.value,
        Caffeine: food.find((n) => n.name === "Caffeine")?.value,
        Campesterol: food.find((n) => n.name === "Campesterol")?.value,
        Carotene_alpha: food.find((n) => n.name === "Carotene_alpha")?.value,
        Carotene_beta: food.find((n) => n.name === "Carotene_beta")?.value,
        Vitamin_D3_cholecalciferol: food.find(
          (n) => n.name === "Vitamin_D3_cholecalciferol"
        )?.value,
        Choline_total: food.find((n) => n.name === "Choline_total")?.value,
        Cryptoxanthin_beta: food.find((n) => n.name === "Cryptoxanthin_beta")?.value,
        Copper_Cu: food.find((n) => n.name === "Copper_Cu")?.value,
        Cystine: food.find((n) => n.name === "Cystine")?.value,
        Vitamin_D2_ergocalciferol: food.find(
          (n) => n.name === "Vitamin_D2_ergocalciferol"
        )?.value,
        Fatty_acids_total_monounsaturated: food.find(
          (n) => n.name === "Fatty_acids_total_monounsaturated"
        )?.value,
        Fatty_acids_total_polyunsaturated: food.find(
          (n) => n.name === "Fatty_acids_total_polyunsaturated"
        )?.value,
        Fatty_acids_total_trans_monoenoic: food.find(
          (n) => n.name === "Fatty_acids_total_trans_monoenoic"
        )?.value,
        Fatty_acids_total_trans_polyenoic: food.find(
          (n) => n.name === "Fatty_acids_total_trans_polyenoic"
        )?.value,
        Fluoride_F: food.find((n) => n.name === "Fluoride_F")?.value,
        Folate_total: food.find((n) => n.name === "Folate_total")?.value,
        Folic_acid: food.find((n) => n.name === "Folic_acid")?.value,
        Folate_DFE: food.find((n) => n.name === "Folate_DFE")?.value,
        Folate_food: food.find((n) => n.name === "Folate_food")?.value,
        Fructose: food.find((n) => n.name === "Fructose")?.value,
        Galactose: food.find((n) => n.name === "Galactose")?.value,
        Glutamic_acid: food.find((n) => n.name === "Glutamic_acid")?.value,
        Glucose_dextrose: food.find((n) => n.name === "Glucose_dextrose")?.value,
        Glycine: food.find((n) => n.name === "Glycine")?.value,
        Histidine: food.find((n) => n.name === "Histidine")?.value,
        Hydroxyproline: food.find((n) => n.name === "Hydroxyproline")?.value,
        Isoleucine: food.find((n) => n.name === "Isoleucine")?.value,
        Lactose: food.find((n) => n.name === "Lactose")?.value,
        Leucine: food.find((n) => n.name === "Leucine")?.value,
        Lutein_zeaxanthin: food.find((n) => n.name === "Lutein_zeaxanthin")?.value,
        Lycopene: food.find((n) => n.name === "Lycopene")?.value,
        Lysine: food.find((n) => n.name === "Lysine")?.value,
        Maltose: food.find((n) => n.name === "Maltose")?.value,
        Methionine: food.find((n) => n.name === "Methionine")?.value,
        Magnesium_Mg: food.find((n) => n.name === "Magnesium_Mg")?.value,
        Menaquinone_4: food.find((n) => n.name === "Menaquinone_4")?.value,
        Manganese_Mn: food.find((n) => n.name === "Manganese_Mn")?.value,
        Niacin: food.find((n) => n.name === "Niacin")?.value,
        Vitamin_E_added: food.find((n) => n.name === "Vitamin_E_added")?.value,
        Vitamin_B_12_added: food.find((n) => n.name === "Vitamin_B_12_added")?.value,
        Adjusted_Protein: food.find((n) => n.name === "Adjusted_Protein")?.value,
        Phosphorus_P: food.find((n) => n.name === "Phosphorus_P")?.value,
        Pantothenic_acid: food.find((n) => n.name === "Pantothenic_acid")?.value,
        Phenylalanine: food.find((n) => n.name === "Phenylalanine")?.value,
        Phytosterols: food.find((n) => n.name === "Phytosterols")?.value,
        Proline: food.find((n) => n.name === "Proline")?.value,
        Retinol: food.find((n) => n.name === "Retinol")?.value,
        Riboflavin: food.find((n) => n.name === "Riboflavin")?.value,
        Selenium_Se: food.find((n) => n.name === "Selenium_Se")?.value,
        Serine: food.find((n) => n.name === "Serine")?.value,
        Beta_sitosterol: food.find((n) => n.name === "Beta_sitosterol")?.value,
        Starch: food.find((n) => n.name === "Starch")?.value,
        Stigmasterol: food.find((n) => n.name === "Stigmasterol")?.value,
        Sucrose: food.find((n) => n.name === "Sucrose")?.value,
        Theobromine: food.find((n) => n.name === "Theobromine")?.value,
        Thiamin: food.find((n) => n.name === "Thiamin")?.value,
        Threonine: food.find((n) => n.name === "Threonine")?.value,
        Vitamin_E_alpha_tocopherol: food.find(
          (n) => n.name === "Vitamin_E_alpha_tocopherol"
        )?.value,
        Tocopherol_beta: food.find((n) => n.name === "Tocopherol_beta")?.value,
        Tocopherol_delta: food.find((n) => n.name === "Tocopherol_delta")?.value,
        Tocopherol_gamma: food.find((n) => n.name === "Tocopherol_gamma")?.value,
        Tryptophan: food.find((n) => n.name === "Tryptophan")?.value,
        Tyrosine: food.find((n) => n.name === "Tyrosine")?.value,
        Valine: food.find((n) => n.name === "Valine")?.value,
        Vitamin_A_IU: food.find((n) => n.name === "Vitamin_A_IU")?.value,
        Vitamin_A_RAE: food.find((n) => n.name === "Vitamin_A_RAE")?.value,
        Vitamin_B_12: food.find((n) => n.name === "Vitamin_B_12")?.value,
        Vitamin_B_6: food.find((n) => n.name === "Vitamin_B_6")?.value,
        Vitamin_C_total_ascorbic_acid: food.find(
          (n) => n.name === "Vitamin_C_total_ascorbic_acid"
        )?.value,
        Vitamin_D_D2_D3: food.find((n) => n.name === "Vitamin_D_D2_D3")?.value,
        Vitamin_K_phylloquinone: food.find(
          (n) => n.name === "Vitamin_K_phylloquinone"
        )?.value,
        Dihydrophylloquinone: food.find((n) => n.name === "Dihydrophylloquinone")
          ?.value,
        Water: food.find((n) => n.name === "Water")?.value,
        Zinc_Zn: food.find((n) => n.name === "Zinc_Zn")?.value,
      };

    const newUser = new nutrientSchema(nutrientData);
    await newUser.save();
    console.log(`Saved: ${foodname}`);
  } catch (err) {
    console.error(`Error processing ${item}:`, err.message);
    arr.push(item);
  }
};

const main = async () => {
    await connectDB();
    for (let i = 0; i < 200; i++) {
        const item = foodItems[i];
        await processFoodItem(item);
         // Add delay between requests
      }
      mongoose.connection.close();
      console.log("Failed items:", arr);
//   for (let i = 0; i < 100; i++) {
//     const item = indianFoods[i];
//     await processFoodItem(item);
//     await new Promise((resolve) => setTimeout(resolve, 1000)); // Add delay between requests
//   }
//   console.log("Failed items:", arr);
};

main();
