const mongoose = require('mongoose');

const nutrientSchema = new mongoose.Schema({
    foodname: { type: String, required: true },
    quantity: { type: Number, required: true },

    // Macronutrients
Calcium: {type: Number, default: 0 },
Carbohydrate: {type: Number, default: 0 },
Cholesterol: {type: Number, default: 0 },
Fatty_acids_total_saturated: {type: Number, default: 0 },
Total_lipid_fat: {type: Number, default: 0 },
Fatty_acids_total_trans: {type: Number, default: 0 },
Iron_Fe: {type: Number, default: 0 },
Fiber_total_dietary: {type: Number, default: 0 },
Potassium_K: {type: Number, default: 0 },
Sodium_Na: {type: Number, default: 0 },
Protein: {type: Number, default: 0 },
Sugars_total: {type: Number, default: 0 },
Sugars_added: {type: Number, default: 0 },
Vitamin_D: {type: Number, default: 0 },
Sugar_Alcohol: {type: Number, default: 0 },
Erythritol: {type: Number, default: 0 },
Allulose: {type: Number, default: 0 },
Glycerin: {type: Number, default: 0 },
Xylitol: {type: Number, default: 0 },
Sorbitol: {type: Number, default: 0 },
Mannitol: {type: Number, default: 0 },
Maltitol: {type: Number, default: 0 },
Isomalt: {type: Number, default: 0 },
Lactitol: {type: Number, default: 0 },
Alanine: {type: Number, default: 0 },
Alcohol_ethyl: {type: Number, default: 0 },
Arginine: {type: Number, default: 0 },
Ash: {type: Number, default: 0 },
Aspartic_acid: {type: Number, default: 0 },
Betaine: {type: Number, default: 0 },
Caffeine: {type: Number, default: 0 },
Campesterol: {type: Number, default: 0 },
Carotene_alpha: {type: Number, default: 0 },
Carotene_beta: {type: Number, default: 0 },
Vitamin_D3_cholecalciferol: {type: Number, default: 0 },
Choline_total: {type: Number, default: 0 },
Cryptoxanthin_beta: {type: Number, default: 0 },
Copper_Cu: {type: Number, default: 0 },
Cystine: {type: Number, default: 0 },
Energy: {type: Number, default: 0 },
Vitamin_D2_ergocalciferol: {type: Number, default: 0 },
Fatty_acids_total_monounsaturated: {type: Number, default: 0 },
Fatty_acids_total_polyunsaturated: {type: Number, default: 0 },
Fatty_acids_total_trans_monoenoic: {type: Number, default: 0 },
Fatty_acids_total_trans_polyenoic: {type: Number, default: 0 },
Fluoride_F: {type: Number, default: 0 },
Folate_total: {type: Number, default: 0 },
Folic_acid: {type: Number, default: 0 },
Folate_DFE: {type: Number, default: 0 },
Folate_food: {type: Number, default: 0 },
Fructose: {type: Number, default: 0 },
Galactose: {type: Number, default: 0 },
Glutamic_acid: {type: Number, default: 0 },
Glucose_dextrose: {type: Number, default: 0 },
Glycine: {type: Number, default: 0 },
Histidine: {type: Number, default: 0 },
Hydroxyproline: {type: Number, default: 0 },
Isoleucine: {type: Number, default: 0 },
Lactose: {type: Number, default: 0 },
Leucine: {type: Number, default: 0 },
Lutein_zeaxanthin: {type: Number, default: 0 },
Lycopene: {type: Number, default: 0 },
Lysine: {type: Number, default: 0 },
Maltose: {type: Number, default: 0 },
Methionine: {type: Number, default: 0 },
Magnesium_Mg: {type: Number, default: 0 },
Menaquinone_4: {type: Number, default: 0 },
Manganese_Mn: {type: Number, default: 0 },
Niacin: {type: Number, default: 0 },
Vitamin_E_added: {type: Number, default: 0 },
Vitamin_B_12_added: {type: Number, default: 0 },
Adjusted_Protein: {type: Number, default: 0 },

Phosphorus_P: {type: Number, default: 0 },
Pantothenic_acid: {type: Number, default: 0 },
Phenylalanine: {type: Number, default: 0 },
Phytosterols: {type: Number, default: 0 },
Proline: {type: Number, default: 0 },
Retinol: {type: Number, default: 0 },
Riboflavin: {type: Number, default: 0 },
Selenium_Se: {type: Number, default: 0 },
Serine: {type: Number, default: 0 },
Beta_sitosterol: {type: Number, default: 0 },
Starch: {type: Number, default: 0 },
Stigmasterol: {type: Number, default: 0 },
Sucrose: {type: Number, default: 0 },
Theobromine: {type: Number, default: 0 },
Thiamin: {type: Number, default: 0 },
Threonine: {type: Number, default: 0 },
Vitamin_E_alpha_tocopherol: {type: Number, default: 0 },
Tocopherol_beta: {type: Number, default: 0 },
Tocopherol_delta: {type: Number, default: 0 },
Tocopherol_gamma: {type: Number, default: 0 },
Tryptophan: {type: Number, default: 0 },
Tyrosine: {type: Number, default: 0 },
Valine: {type: Number, default: 0 },
Vitamin_A_IU: {type: Number, default: 0 },
Vitamin_A_RAE: {type: Number, default: 0 },
Vitamin_B_12: {type: Number, default: 0 },
Vitamin_B_6: {type: Number, default: 0 },
Vitamin_C_total_ascorbic_acid: {type: Number, default: 0 },
Vitamin_D_D2_D3: {type: Number, default: 0 },
Vitamin_K_phylloquinone: {type: Number, default: 0 },
Dihydrophylloquinone: {type: Number, default: 0 },
Water: {type: Number, default: 0 },
Zinc_Zn: {type: Number, default: 0 },
});

const Nutrient = mongoose.model('Nutrient', nutrientSchema);

module.exports = Nutrient;
